default_chain: stride
chains:
  stride:
    key: test
    chain-id: STRIDE_1
    rpc-addr: http://stride1:26657
    grpc-addr: http://stride1:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 0.1
    gas-prices: 0.00ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    output-format: json
    sign-mode: direct
  liquidstaking:
    key: test
    chain-id: GAIA_1
    rpc-addr: http://gaia1:26657
    grpc-addr: http://gaia1:9090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 0.1
    gas-prices: 0.00stake
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    output-format: json
    sign-mode: direct
# default_chain: cosmoshub
# chains:
#   cosmoshub:
#     key: default
#     chain-id: cosmoshub-4
#     rpc-addr: https://cosmoshub-4.technofractal.com:443
#     grpc-addr: https://gprc.cosmoshub-4.technofractal.com:443
#     account-prefix: cosmos
#     keyring-backend: test
#     gas-adjustment: 1.2
#     gas-prices: 0.01uatom
#     key-directory: /icq/.icq/keys
#     debug: false
#     timeout: 20s
#     output-format: json
#     sign-mode: direct
#   osmosis:
#     key: default
#     chain-id: osmosis-1
#     rpc-addr: https://osmosis-1.technofractal.com:443
#     grpc-addr: https://gprc.osmosis-1.technofractal.com:443
#     account-prefix: osmo
#     keyring-backend: test
#     gas-adjustment: 1.2
#     gas-prices: 0.01uosmo
#     key-directory: /icq/.icq/keys
#     debug: false
#     timeout: 20s
#     output-format: json
#     sign-mode: direct
# cl: {}
